### 密码模式登录

POST http://localhost:9999/oauth2/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=admin&password=123456&client_id=vue&client_secret=123456&scope=openid

> {% client.global.set("token", "Bearer " + response.body.access_token) %}

### 获取当前用户信息
GET http://localhost:9999/api/userinfo
Authorization: {{token}}