### 分页查询
GET http://127.0.0.1:9999/permissions
Authorization: {{token}}
Accept: application/json

### 根据id查看
GET http://127.0.0.1:9999/permissions/1
Authorization: {{token}}
Accept: application/json

### 新增权限
POST http://127.0.0.1:9999/permissions
Content-Type: application/json
Authorization: {{token}}

{
  "type": "MENU",
  "code": "permissions",
  "name": "查询权限列表",
  "description": "查询权限列表",
  "sortIndex": 102,
  "createTime": 1654138136000
}