server:
  servlet:
    context-path: /
spring:
  mail:
    host: smtp.yeah.net
    username: koala_projects@yeah.net
    password: 123456
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      host: 127.0.0.1
      database: test
      auto-index-creation: true

logging:
  level:
    cn.koala: debug
  file:
    name: logs/koala-admin-server.log

wx:
  cp:
    corp-id: corp-id
    corp-secret: corp-secret
    agent-id: 10001

koala:
  admin:
    server:
      fallback:
        strategy: mail
        maintainer:
          email: 'koala_projects@yeah.net'