server:
  port: 9000
  servlet:
    context-path: /
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/koala_demo?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: koala
    password: Koala@2023
  jackson:
    serialization:
      write-dates-as-timestamps: true
      indent_output: true
      fail_on_empty_beans: false
    default-property-inclusion: non_empty
    deserialization:
      fail_on_unknown_properties: false
  data:
    web:
      pageable:
        default-page-size: 50
        max-page-size: 2000
  security:
    oauth2:
      resourceserver:
        opaque-token:
          introspection-uri: http://127.0.0.1:9000/oauth2/introspect
          client-id: koala-admin
          client-secret: 123456

mybatis:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    cn.koala: debug
  file:
    name: logs/koala-demo.log

springdoc:
  swagger-ui:
    doc-expansion: none
    tags-sorter: alpha

koala:
  code-gen:
    path: /tmp/koala/code-gen/
    table-prefix: k_
    package-name: cn.koala.demo
  log:
    ignored-patterns:
      - "[部门|字典|权限|角色|设置].*"
  security:
    authorization-server:
      custom-login-page: true
    resource-server:
      permit-all-patterns:
        - /api/code-gen/file/**
  system:
    admin-register: false
    permission-registrars:
      system:
        enabled: false
        overwritten: true
      code-gen:
        enabled: false
        overwritten: true
      database:
        enabled: false
        overwritten: true
      template:
        enabled: false
        overwritten: true
      log:
        enabled: false
        overwritten: true
      login-log:
        enabled: false
        overwritten: true